// flow-typed signature: 09faea429a2d2f820dcebcb1c97f83fe
// flow-typed version: <<STUB>>/licensor_v^4.0.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'licensor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'licensor' {
  declare module.exports: any;
}
